package com.edgedx.covid.model;

public enum Nationality {
	AFGHANISTAN("Afghan"),
	ALAND_ISLANDS("Aland Island"),
	ALBANIA("Albanian"),
	ALGERIA("Algerian"),
	AMERICAN_SAMOA("American Samoan"),
	ANDORRA("Andorran"),
	ANGOLA("Angolan"),
	ANGUILLA("Anguillan"),
	ANTARCTICA("Antarctic"),
	ANTIGUA_AND_BARBUDA("Antiguan or Barbudan"),
	ARGENTINA("Argentine"),
	ARMENIA("Armenian"),
	ARUBA("Aruban"),
	AUSTRALIA("Australian"),
	AUSTRIA("Austrian"),
	AZERBAIJAN("Azerbaijani, Azeri"),
	BAHAMAS("Bahamian"),
	BAHRAIN("Bahraini"),
	BANGLADESH("Bangladeshi"),
	BARBADOS("Barbadian"),
	BELARUS("Belarusian"),
	BELGIUM("Belgian"),
	BELIZE("Belizean"),
	BENIN("Beninese, Beninois"),
	BERMUDA("Bermudian, Bermudan"),
	BHUTAN("Bhutanese"),
	BOLIVIA("Bolivian"),
	BONAIRE_SINT_EUSTATIUS_AND_SABA("Bonaire"),
	BOSNIA_AND_HERZEGOVINA("Bosnian or Herzegovinian"),
	BOTSWANA("Motswana, Botswanan"),
	BOUVET_ISLAND("Bouvet Island"),
	BRAZIL("Brazilian"),
	BRITISH_INDIAN_OCEAN_TERRITORY("BIOT"),
	BRUNEI_DARUSSALAM("Bruneian"),
	BULGARIA("Bulgarian"),
	BURKINA_FASO("Burkinabe"),
	BURUNDI("Burundian"),
	CABO_VERDE("Cabo Verdean"),
	CAMBODIA("Cambodian"),
	CAMEROON("Cameroonian"),
	CANADA("Canadian"),
	CAYMAN_ISLANDS("Caymanian"),
	CENTRAL_AFRICAN_REPUBLIC("Central African"),
	CHAD("Chadian"),
	CHILE("Chilean"),
	CHINA("Chinese"),
	CHRISTMAS_ISLAND("Christmas Island"),
	COCOS__ISLANDS("Cocos Island"),
	COLOMBIA("Colombian"),
	COMOROS("Comoran, Comorian"),
	CONGO("Congolese"),
	COOK_ISLANDS("Cook Island"),
	COSTA_RICA("Costa Rican"),
	COTE_DIVOIRE("Ivorian"),
	CROATIA("Croatian"),
	CUBA("Cuban"),
	CURACAO("Curacaoan"),
	CYPRUS("Cypriot"),
	CZECH_REPUBLIC("Czech"),
	DENMARK("Danish"),
	DJIBOUTI("Djiboutian"),
	DOMINICA("Dominican"),
	DOMINICAN_REPUBLIC("Dominican"),
	ECUADOR("Ecuadorian"),
	EGYPT("Egyptian"),
	EL_SALVADOR("Salvadoran"),
	EQUATORIAL_GUINEA("Equatorial Guinean, Equatoguinean"),
	ERITREA("Eritrean"),
	ESTONIA("Estonian"),
	ETHIOPIA("Ethiopian"),
	FALKLAND_ISLANDS("Falkland Island"),
	FAROE_ISLANDS("Faroese"),
	FIJI("Fijian"),
	FINLAND("Finnish"),
	FRANCE("French"),
	FRENCH_GUIANA("French Guianese"),
	FRENCH_POLYNESIA("French Polynesian"),
	FRENCH_SOUTHERN_TERRITORIES("French Southern Territories"),
	GABON("Gabonese"),
	GAMBIA("Gambian"),
	GEORGIA("Georgian"),
	GERMANY("German"),
	GHANA("Ghanaian"),
	GIBRALTAR("Gibraltar"),
	GREECE("Greek, Hellenic"),
	GREENLAND("Greenlandic"),
	GRENADA("Grenadian"),
	GUADELOUPE("Guadeloupe"),
	GUAM("Guamanian, Guambat"),
	GUATEMALA("Guatemalan"),
	GUERNSEY("Channel Island"),
	GUINEA("Guinean"),
	GUINEA_BISSAU("Bissau-Guinean"),
	GUYANA("Guyanese"),
	HAITI("Haitian"),
	HEARD_ISLAND_AND_MCDONALD_ISLANDS("Heard Island or McDonald Islands"),
	VATICAN_CITY_STATE("Vatican"),
	HONDURAS("Honduran"),
	HONG_KONG("Hong Kong, Hong Kongese"),
	HUNGARY("Hungarian, Magyar"),
	ICELAND("Icelandic"),
	INDIA("Indian"),
	INDONESIA("Indonesian"),
	IRAN("Iranian, Persian"),
	IRAQ("Iraqi"),
	IRELAND("Irish"),
	ISLE_OF_MAN("Manx"),
	ISRAEL("Israeli"),
	ITALY("Italian"),
	JAMAICA("Jamaican"),
	JAPAN("Japanese"),
	JERSEY("Channel Island"),
	JORDAN("Jordanian"),
	KAZAKHSTAN("Kazakhstani, Kazakh"),
	KENYA("Kenyan"),
	KIRIBATI("I-Kiribati"),
	KOREA_DEMOCRATIC_REPUBLIC_OF("North Korean"),
	KOREA_REPUBLIC_OF("South Korean"),
	KUWAIT("Kuwaiti"),
	KYRGYZSTAN("Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz"),
	LAO_PEOPLES_DEMOCRATIC_REPUBLIC("Lao, Laotian"),
	LATVIA("Latvian"),
	LEBANON("Lebanese"),
	LESOTHO("Basotho"),
	LIBERIA("Liberian"),
	LIBYA("Libyan"),
	LIECHTENSTEIN("Liechtenstein"),
	LITHUANIA("Lithuanian"),
	LUXEMBOURG("Luxembourg, Luxembourgish"),
	MACAO("Macanese, Chinese"),
	MACEDONIA("Macedonian"),
	MADAGASCAR("Malagasy"),
	MALAWI("Malawian"),
	MALAYSIA("Malaysian"),
	MALDIVES("Maldivian"),
	MALI("Malian, Malinese"),
	MALTA("Maltese"),
	MARSHALL_ISLANDS("Marshallese"),
	MARTINIQUE("Martiniquais, Martinican"),
	MAURITANIA("Mauritanian"),
	MAURITIUS("Mauritian"),
	MAYOTTE("Mahoran"),
	MEXICO("Mexican"),
	MICRONESIA("Micronesian"),
	MOLDOVA("Moldovan"),
	MONACO("Monagasque, Monacan"),
	MONGOLIA("Mongolian"),
	MONTENEGRO("Montenegrin"),
	MONTSERRAT("Montserratian"),
	MOROCCO("Moroccan"),
	MOZAMBIQUE("Mozambican"),
	MYANMAR("Burmese"),
	NAMIBIA("Namibian"),
	NAURU("Nauruan"),
	NEPAL("Nepali, Nepalese"),
	NETHERLANDS("Dutch, Netherlandic"),
	NEW_CALEDONIA("New Caledonian"),
	NEW_ZEALAND("New Zealand, NZ"),
	NICARAGUA("Nicaraguan"),
	NIGER("Nigerien"),
	NIGERIA("Nigerian"),
	NIUE("Niuean"),
	NORFOLK_ISLAND("Norfolk Island"),
	NORTHERN_MARIANA_ISLANDS("Northern Marianan"),
	NORWAY("Norwegian"),
	OMAN("Omani"),
	PAKISTAN("Pakistani"),
	PALAU("Palauan"),
	PALESTINE("Palestinian"),
	PANAMA("Panamanian"),
	PAPUA_NEW_GUINEA("Papua New Guinean, Papuan"),
	PARAGUAY("Paraguayan"),
	PERU("Peruvian"),
	PHILIPPINES("Philippine, Filipino"),
	PITCAIRN("Pitcairn Island"),
	POLAND("Polish"),
	PORTUGAL("Portuguese"),
	PUERTO_RICO("Puerto Rican"),
	QATAR("Qatari"),
	REUNION("Reunionese, Reunionnais"),
	ROMANIA("Romanian"),
	RUSSIAN_FEDERATION("Russian"),
	RWANDA("Rwandan"),
	SAINT_BARTHELEMY("Barthelemois"),
	SAINT_HELENA("Saint Helenian"),
	SAINT_KITTS_AND_NEVIS("Kittitian or Nevisian"),
	SAINT_LUCIA("Saint Lucian"),
	SAINT_MARTIN("Saint-Martinoise"),
	SAINT_PIERRE_AND_MIQUELON("Saint-Pierrais or Miquelonnais"),
	SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincentian, Vincentian"),
	SAMOA("Samoan"),
	SAN_MARINO("Sammarinese"),
	SAUDI_ARABIA("Saudi, Saudi Arabian"),
	SENEGAL("Senegalese"),
	SERBIA("Serbian"),
	SEYCHELLES("Seychellois"),
	SIERRA_LEONE("Sierra Leonean"),
	SINGAPORE("Singaporean"),
	SINT_MAARTEN_DUTCH_PART("Sint Maarten"),
	SLOVAKIA("Slovak"),
	SLOVENIA("Slovenian, Slovene"),
	SOLOMON_ISLANDS("Solomon Island"),
	SOMALIA("Somali, Somalian"),
	SOUTH_AFRICA("South African"),
	SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("South Georgia or South Sandwich Islands"),
	SOUTH_SUDAN("South Sudanese"),
	SPAIN("Spanish"),
	SRI_LANKA("Sri Lankan"),
	SUDAN("Sudanese"),
	SURINAME("Surinamese"),
	SVALBARD_AND_JAN_MAYEN("Svalbard"),
	SWAZILAND("Swazi"),
	SWEDEN("Swedish"),
	SWITZERLAND("Swiss"),
	SYRIAN_ARAB_REPUBLIC("Syrian"),
	TAIWAN("Chinese, Taiwanese"),
	TAJIKISTAN("Tajikistani"),
	TANZANIA("Tanzanian"),
	THAILAND("Thai"),
	TIMOR_LESTE("Timorese"),
	TOGO("Togolese"),
	TOKELAU("Tokelauan"),
	TONGA("Tongan"),
	TRINIDAD_AND_TOBAGO("Trinidadian or Tobagonian"),
	TUNISIA("Tunisian"),
	TURKEY("Turkish"),
	TURKMENISTAN("Turkmen"),
	TURKS_AND_CAICOS_ISLANDS("Turks and Caicos Island"),
	TUVALU("Tuvaluan"),
	UGANDA("Ugandan"),
	UKRAINE("Ukrainian"),
	UNITED_ARAB_EMIRATES("Emirati, Emirian, Emiri"),
	UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND("British, UK"),
	UNITED_STATES_MINOR_OUTLYING_ISLANDS("American"),
	UNITED_STATES_OF_AMERICA("American"),
	URUGUAY("Uruguayan"),
	UZBEKISTAN("Uzbekistani, Uzbek"),
	VANUATU("Ni-Vanuatu, Vanuatuan"),
	VENEZUELA("Venezuelan"),
	VIETNAM("Vietnamese"),
	VIRGIN_ISLANDS_BRITISH("British Virgin Island"),
	VIRGIN_ISLANDS_US("U.S. Virgin Island"),
	WALLIS_AND_FUTUNA("Wallis and Futuna, Wallisian or Futunan"),
	WESTERN_SAHARA("Sahrawi, Sahrawian, Sahraouian"),
	YEMEN("Yemeni"),
	ZAMBIA("Zambian"),
	ZIMBABWE("Zimbabwean");
	
    private String value;
    
    Nationality(String value) {
        this.value = value;
    }
 
    public String getValue() {
        return value;
    }

}
